name: Deploy Supabase Functions

on:
  push:
    branches:
      - main
    paths:
      - backend/**
  workflow_dispatch:

defaults:
  run:
    working-directory: ./backend

jobs:
  deploy-functions:
    name: Deploy Supabase Functions
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: 1.167.4
      - run: supabase functions deploy --project-ref $PROJECT_ID
  deploy-db:
    name: Deploy Supabase Database Migrations
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: 1.167.4
      - run: supabase link --project-ref $PROJECT_ID
      - run: supabase db push
