name: Deploy Supabase Functions

on:
  push:
    branches:
      - main
      - feat/setup-supabase
    paths:
      - backend/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: 1.167.4
      - run: supabase functions deploy --project-ref $PROJECT_ID
