name: PR Frontend Checks

on:
  pull_request:
    branches: ["dev", "main"]
    paths:
      - frontend/**
  workflow_dispatch:

defaults:
  run:
    working-directory: ./frontend

jobs:
  prettier:
    name: Prettier Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: frontend/yarn.lock
      - name: prettier lint
        run: |
          yarn install --frozen-lockfile
          yarn lint
  jest:
    name: Jest Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: frontend/yarn.lock
      - name: unit test
        run: |
          yarn install --frozen-lockfile
          yarn test --passWithNoTests
