name: PR Checks

on:
  pull_request:
    branches:
      - main
    paths:
      - frontend/**

defaults:
  run:
    working-directory: ./frontend

jobs:
  prettier:
    name: Prettier Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: frontend/package-lock.json
      - name: prettier lint
        run: |
        yarn install --frozen-lockfile
        yarn lint
  jest:
    name: Jest Test
    runs-on: ubuntu-22.04
    env:
      NEXT_OMDB_API_KEY: ${{ secrets.NEXT_OMDB_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: frontend/package-lock.json
      - name: unit test
        run: |
        yarn install --frozen-lockfile
        yarn test
