name: Run Prettier Check

on:
  pull_request:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Prettier check
        uses: borales/actions-yarn@v4
        with:
          cmd: lint
